import type { Prisma } from '../../generated/prisma/client.js';

export const vehicleSeedData: Prisma.VehicleCreateManyInput[] = [
  {
    make: 'Toyota',
    model: 'Corolla',
    year: 2023,
    category: 'Sedan',
    description: 'Reliable daily driver with excellent fuel economy and a spacious trunk.',
    price: 22000,
    quantity: 8,
  },
  {
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    category: 'Sedan',
    description: 'Sporty handling with a refined interior and strong resale value.',
    price: 21000,
    quantity: 5,
  },
  {
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    category: 'Truck',
    description: "America's best-selling truck, built for towing and everyday hauling.",
    price: 45000,
    quantity: 3,
  },
  {
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2021,
    category: 'Truck',
    description: 'Heavy-duty capability with a comfortable, tech-forward cabin.',
    price: 42000,
    quantity: 0,
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    category: 'Electric',
    description: 'Long-range electric sedan with Autopilot and minimalist styling.',
    price: 39000,
    quantity: 6,
  },
  {
    make: 'Jeep',
    model: 'Wrangler',
    year: 2022,
    category: 'SUV',
    description: 'Off-road icon with removable doors and a rugged 4x4 drivetrain.',
    price: 38000,
    quantity: 4,
  },
  {
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    category: 'SUV',
    description: 'Family-friendly crossover with best-in-class cargo space.',
    price: 31000,
    quantity: 9,
  },
  {
    make: 'BMW',
    model: '3 Series',
    year: 2021,
    category: 'Sedan',
    description: 'Luxury sport sedan with precise steering and a premium cabin.',
    price: 34000,
    quantity: 2,
  },
  {
    make: 'Mazda',
    model: 'MX-5 Miata',
    year: 2023,
    category: 'Convertible',
    description: 'Lightweight roadster built purely for driving enjoyment.',
    price: 29000,
    quantity: 0,
  },
  {
    make: 'Subaru',
    model: 'Outback',
    year: 2022,
    category: 'SUV',
    description: 'Standard all-wheel drive and generous ground clearance for any weather.',
    price: 28000,
    quantity: 7,
  },
  {
    make: 'Kia',
    model: 'Soul',
    year: 2021,
    category: 'Hatchback',
    description: 'Boxy, practical, and affordable with surprising cargo room.',
    price: 19000,
    quantity: 10,
  },
  {
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2022,
    category: 'Minivan',
    description: 'Family hauler with stow-and-go seating and available hybrid drivetrain.',
    price: 33000,
    quantity: 5,
  },
  {
    make: 'Audi',
    model: 'A4',
    year: 2023,
    category: 'Sedan',
    description: 'Understated luxury with quattro all-wheel drive available.',
    price: 41000,
    quantity: 1,
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    category: 'SUV',
    description: 'Bold styling with a long warranty and strong safety ratings.',
    price: 30000,
    quantity: 6,
  },
  {
    make: 'Porsche',
    model: '911',
    year: 2022,
    category: 'Coupe',
    description: 'The benchmark sports coupe, equally at home on track or street.',
    price: 101000,
    quantity: 2,
  },
];
